arcTest/arcTest/Models/ArcFile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using System.Data;
using System.Data.Sql;
using System.Data.SqlClient;


namespace arcTest.Models
{
    public class ArcFile
    {
        private Guid ID { get; set; }
        public string Name { get; set; }
        public byte[] Contents { get; set; }

        public ArcFile( string fname )
        {
            this.ID =Guid.NewGuid();
            this.Name = fname;
        }

        public void ConvertToByte(HttpPostedFileBase file)
        {
            this.Contents = null;
            BinaryReader rdr = new BinaryReader(file.InputStream);
            this.Contents = rdr.ReadBytes((int)file.ContentLength);
        }

        public void SaveToDB()
        {
            SqlConnection cn = new SqlConnection("data source=(LocalDb)\\v12.0;initial catalog=arcTest;integrated security=True;MultipleActiveResultSets=True;");

            SqlCommand cmd = new SqlCommand("INSERT INTO dbo.ArcFile ( ID, Name, Contents) VALUES ( @ID, @NAME, @Content)", cn);

            cmd.Parameters.Add("@ID", SqlDbType.NVarChar, 255).Value = this.ID.ToString();
            cmd.Parameters.Add("@NAME", SqlDbType.NVarChar, 255).Value = this.Name;
            cmd.Parameters.Add("@Content", SqlDbType.VarBinary).Value = this.Contents;

            cn.Open();
            cmd.ExecuteNonQuery();
            cn.Close();
        }

    }
}

arcTest/arcTest/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading;

using arcTest.Models;

namespace FileUploadMVC.Controllers
{
    public class FilesController : Controller
    {
        // GET: Upload    
        public ActionResult AsynFileUpload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AsynFileUpload(HttpPostedFileBase file)
        {
            Thread.Sleep(5000);

            if (file != null && file.ContentLength > 0)
            {
                if (file.ContentLength <= 2000000)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                    file.SaveAs(path);

                    ArcFile dbFile = new ArcFile(file.FileName);
                    dbFile.ConvertToByte(file);

                    dbFile.SaveToDB();

                }
                else
                {
                    Session["Error"] = " Maximum file size is 2MB. ";

                }

            }

            return new JsonResult
            {
                Data = "Upload completed!"
            };


        }
    }
}

arcTest/arcTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace arcTest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

arcTest/arcTest/Views/Files/AsynFileUpload.cshtml
@{
    ViewBag.Title = "FileUpload";
    Layout = "~/Views/Shared/_Layout.cshtml";
} 
<style>
    .progress {
        position: relative;
        width: 450 px;
        border: 1 px solid# ddd;
        padding: 1 px;
    }

        .progress - bar {
            width: 0 px;
            height: 30 px;
            background-color: green;
        }
</style>

<h2> File Upload </h2>

<div id="container">
    <button id="btnNewFile" onclick="addFileDiv()">Add New file</button>

    @using (Ajax.BeginForm("AsynFileUpload", "UploadFile", new AjaxOptions()
    {
        HttpMethod = "post"
    }, new
    {
        enctype = "multipart/form-data"
    }))
    {
        @Html.AntiForgeryToken()

        <div id="orig">
            <h4> File upload </h4>
            <input type="file" name="file" id="ful" />
            <input type="submit" value="upload file" />
            <div class="progress">
                <div class="progress-bar" id="progressBar"> 0 % </div>
            </div>
            <div class="status"> </div>

            <hr />
        </div>
    


    @section scripts {
        <script src="http://malsup.github.io/jquery.form.js"> </script>
        <script>
            (
                function () {
                    var bar = $('.progress-bar');
                    var percent = $('.progress-bar');
                    var status = $('.status');

                    $('form').ajaxForm({
                        beforeSend: function () {
                            status.empty();
                            var percentValue = '0%';
                            bar.width(percentValue);
                            percent.html(percentValue);
                        },
                        uploadProgress: function (event, position, total, percentComplete) {
                            var percentValue = percentComplete + '%';
                            bar.width(percentValue);
                            percent.html(percentValue);
                            status.html('In progress..');
                        },
                        success: function (d) {
                            var percentValue = '100%';
                            bar.width(percentValue);
                            percent.html(percentValue);
                            $('#fu1').val('');
                        },
                        complete: function (xhr) {
                            status.html(xhr.responseText);
                        }
                    });
                })();

            var fileCount = 1;

            function addFileDiv() {
                var temp = document.getElementById('orig').cloneNode(true);

                var cont = document.getElementById("container");
                cont.appendChild(temp);

            }
        </script>
    }
}

arcTest/arcTest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

arcTest/arcTest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

arcTest/arcTest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Arcanys Test</h1>
    <p class="lead">Click @Html.ActionLink("HERE", "AsynFileUpload", "Files") to go to the File Upload page</p>
</div>

<div class="row">
    <div class="col-md-4">
        <p class="lead">Click @Html.ActionLink("HERE", "AsynFileUpload", "Files") to go to the File Upload page</p>
    </div>
</div>

arcTest/arcTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ArcTest", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("File Upload", "AsynFileUpload", "Files")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>